name: run-tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php: [8.4, 8.3, 8.2]
                laravel: [12.*, 11.*, 10.*]
                dependency-version: [prefer-stable]
                include:
                    -   laravel: 12.*
                        testbench: 10.*
                        phpunit: ^11.0
                    -   laravel: 11.*
                        testbench: 9.*
                        phpunit: ^11.0
                    -   laravel: 10.*
                        testbench: 8.*
                        phpunit: ^10.0

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
                    coverage: none

            -   name: Install dependencies
                run: |
                    composer config audit.block-insecure false
                    composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "phpunit/phpunit:${{ matrix.phpunit }}" --no-interaction --no-update --dev
                    composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-audit

            -   name: Execute tests
                run: vendor/bin/phpunit
            
            -   name: Run Static Analysis (PHPStan)
                run: vendor/bin/phpstan analyse
